apiVersion: v1
kind: Namespace
metadata:
  name: matrix
spec: {}
status: {}

---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-reader
spec:
  type: bindings.kubernetes
  version: v1
  metadata:
  - name: namespace
    value: matrix
  - name: resyncPeriodInSec
    value: "15"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: matrix
  name: k8s-reader
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-reader-binding
  namespace: matrix # same as above
subjects:
- kind: ServiceAccount
  name: default # or as need be, can be changed
  namespace: default # same as above
roleRef:
  kind: Role
  name: k8s-reader # same as the one above
  apiGroup: ""