apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secrets
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: your_keyvault_name
  - name: spnClientId
    value: your_managed_identity_client_id
